// Benchmark "b06_C.blif" written by ABC on Mon Sep 21 03:01:16 2020

module \b06_C.blif  ( 
    ACKOUT_REG_SCAN_IN, CONT_EQL, STATE_REG_2__SCAN_IN,
    STATE_REG_1__SCAN_IN, STATE_REG_0__SCAN_IN, CC_MUX_REG_2__SCAN_IN,
    CC_MUX_REG_1__SCAN_IN, USCITE_REG_2__SCAN_IN, USCITE_REG_1__SCAN_IN,
    ENABLE_COUNT_REG_SCAN_IN,
    CC_MUX_2_, CC_MUX_1_, USCITE_2_, USCITE_1_, ENABLE_COUNT, ACKOUT,
    STATE_REG_2__SCAN_OUT, STATE_REG_1__SCAN_OUT, STATE_REG_0__SCAN_OUT,
    CC_MUX_REG_2__SCAN_OUT, CC_MUX_REG_1__SCAN_OUT, USCITE_REG_2__SCAN_OUT,
    USCITE_REG_1__SCAN_OUT, ENABLE_COUNT_REG_SCAN_OUT, ACKOUT_REG_SCAN_OUT  );
  input  ACKOUT_REG_SCAN_IN, CONT_EQL, STATE_REG_2__SCAN_IN,
    STATE_REG_1__SCAN_IN, STATE_REG_0__SCAN_IN, CC_MUX_REG_2__SCAN_IN,
    CC_MUX_REG_1__SCAN_IN, USCITE_REG_2__SCAN_IN, USCITE_REG_1__SCAN_IN,
    ENABLE_COUNT_REG_SCAN_IN;
  output CC_MUX_2_, CC_MUX_1_, USCITE_2_, USCITE_1_, ENABLE_COUNT, ACKOUT,
    STATE_REG_2__SCAN_OUT, STATE_REG_1__SCAN_OUT, STATE_REG_0__SCAN_OUT,
    CC_MUX_REG_2__SCAN_OUT, CC_MUX_REG_1__SCAN_OUT, USCITE_REG_2__SCAN_OUT,
    USCITE_REG_1__SCAN_OUT, ENABLE_COUNT_REG_SCAN_OUT, ACKOUT_REG_SCAN_OUT;
  wire new_n26_, new_n27_, new_n28_, new_n29_, new_n31_, new_n32_, new_n35_,
    new_n39_;
  INVX1    g00(.A(STATE_REG_2__SCAN_IN), .Y(new_n26_));
  INVX1    g01(.A(STATE_REG_0__SCAN_IN), .Y(new_n27_));
  OR2X1    g02(.A(STATE_REG_0__SCAN_IN), .B(STATE_REG_1__SCAN_IN), .Y(new_n28_));
  OR2X1    g03(.A(STATE_REG_1__SCAN_IN), .B(STATE_REG_2__SCAN_IN), .Y(new_n29_));
  OAI22X1  g04(.A0(new_n29_), .A1(new_n27_), .B0(new_n28_), .B1(new_n26_), .Y(STATE_REG_2__SCAN_OUT));
  INVX1    g05(.A(STATE_REG_1__SCAN_IN), .Y(new_n31_));
  OR2X1    g06(.A(STATE_REG_0__SCAN_IN), .B(STATE_REG_2__SCAN_IN), .Y(new_n32_));
  OAI22X1  g07(.A0(new_n32_), .A1(new_n31_), .B0(new_n28_), .B1(new_n26_), .Y(STATE_REG_1__SCAN_OUT));
  NAND3X1  g08(.A(new_n27_), .B(new_n31_), .C(STATE_REG_2__SCAN_IN), .Y(STATE_REG_0__SCAN_OUT));
  NAND2X1  g09(.A(STATE_REG_0__SCAN_IN), .B(STATE_REG_2__SCAN_IN), .Y(new_n35_));
  NAND3X1  g10(.A(new_n35_), .B(new_n32_), .C(new_n31_), .Y(CC_MUX_REG_1__SCAN_OUT));
  NOR2X1   g11(.A(new_n28_), .B(new_n26_), .Y(USCITE_REG_2__SCAN_OUT));
  NOR2X1   g12(.A(new_n35_), .B(new_n31_), .Y(new_n39_));
  OAI22X1  g13(.A0(new_n39_), .A1(CONT_EQL), .B0(new_n32_), .B1(new_n31_), .Y(ENABLE_COUNT_REG_SCAN_OUT));
  ONE      g14(.Y(USCITE_REG_1__SCAN_OUT));
  BUFX1    g15(.A(CC_MUX_REG_2__SCAN_IN), .Y(CC_MUX_2_));
  BUFX1    g16(.A(CC_MUX_REG_1__SCAN_IN), .Y(CC_MUX_1_));
  BUFX1    g17(.A(USCITE_REG_2__SCAN_IN), .Y(USCITE_2_));
  BUFX1    g18(.A(USCITE_REG_1__SCAN_IN), .Y(USCITE_1_));
  BUFX1    g19(.A(ENABLE_COUNT_REG_SCAN_IN), .Y(ENABLE_COUNT));
  BUFX1    g20(.A(ACKOUT_REG_SCAN_IN), .Y(ACKOUT));
  OAI22X1  g21(.A0(new_n29_), .A1(new_n27_), .B0(new_n28_), .B1(new_n26_), .Y(CC_MUX_REG_2__SCAN_OUT));
  OAI22X1  g22(.A0(new_n39_), .A1(CONT_EQL), .B0(new_n32_), .B1(new_n31_), .Y(ACKOUT_REG_SCAN_OUT));
endmodule


