// Benchmark "b09_C.blif" written by ABC on Mon Sep 21 03:03:07 2020

module \b09_C.blif  ( 
    X, D_OUT_REG_7__SCAN_IN, D_OUT_REG_6__SCAN_IN, D_OUT_REG_5__SCAN_IN,
    D_OUT_REG_4__SCAN_IN, D_OUT_REG_3__SCAN_IN, D_OUT_REG_2__SCAN_IN,
    D_OUT_REG_1__SCAN_IN, D_OUT_REG_0__SCAN_IN, OLD_REG_7__SCAN_IN,
    OLD_REG_6__SCAN_IN, OLD_REG_5__SCAN_IN, OLD_REG_4__SCAN_IN,
    OLD_REG_3__SCAN_IN, OLD_REG_2__SCAN_IN, OLD_REG_1__SCAN_IN,
    OLD_REG_0__SCAN_IN, Y_REG_SCAN_IN, STATO_REG_1__SCAN_IN,
    STATO_REG_0__SCAN_IN, D_IN_REG_8__SCAN_IN, D_IN_REG_7__SCAN_IN,
    D_IN_REG_6__SCAN_IN, D_IN_REG_5__SCAN_IN, D_IN_REG_4__SCAN_IN,
    D_IN_REG_3__SCAN_IN, D_IN_REG_2__SCAN_IN, D_IN_REG_1__SCAN_IN,
    Y, D_OUT_REG_7__SCAN_OUT, D_OUT_REG_6__SCAN_OUT, D_OUT_REG_5__SCAN_OUT,
    D_OUT_REG_4__SCAN_OUT, D_OUT_REG_3__SCAN_OUT, D_OUT_REG_2__SCAN_OUT,
    D_OUT_REG_1__SCAN_OUT, D_OUT_REG_0__SCAN_OUT, OLD_REG_7__SCAN_OUT,
    OLD_REG_6__SCAN_OUT, OLD_REG_5__SCAN_OUT, OLD_REG_4__SCAN_OUT,
    OLD_REG_3__SCAN_OUT, OLD_REG_2__SCAN_OUT, OLD_REG_1__SCAN_OUT,
    OLD_REG_0__SCAN_OUT, Y_REG_SCAN_OUT, STATO_REG_1__SCAN_OUT,
    STATO_REG_0__SCAN_OUT, D_IN_REG_8__SCAN_OUT, D_IN_REG_7__SCAN_OUT,
    D_IN_REG_6__SCAN_OUT, D_IN_REG_5__SCAN_OUT, D_IN_REG_4__SCAN_OUT,
    D_IN_REG_3__SCAN_OUT, D_IN_REG_2__SCAN_OUT, D_IN_REG_1__SCAN_OUT,
    D_IN_REG_0__SCAN_OUT  );
  input  X, D_OUT_REG_7__SCAN_IN, D_OUT_REG_6__SCAN_IN,
    D_OUT_REG_5__SCAN_IN, D_OUT_REG_4__SCAN_IN, D_OUT_REG_3__SCAN_IN,
    D_OUT_REG_2__SCAN_IN, D_OUT_REG_1__SCAN_IN, D_OUT_REG_0__SCAN_IN,
    OLD_REG_7__SCAN_IN, OLD_REG_6__SCAN_IN, OLD_REG_5__SCAN_IN,
    OLD_REG_4__SCAN_IN, OLD_REG_3__SCAN_IN, OLD_REG_2__SCAN_IN,
    OLD_REG_1__SCAN_IN, OLD_REG_0__SCAN_IN, Y_REG_SCAN_IN,
    STATO_REG_1__SCAN_IN, STATO_REG_0__SCAN_IN, D_IN_REG_8__SCAN_IN,
    D_IN_REG_7__SCAN_IN, D_IN_REG_6__SCAN_IN, D_IN_REG_5__SCAN_IN,
    D_IN_REG_4__SCAN_IN, D_IN_REG_3__SCAN_IN, D_IN_REG_2__SCAN_IN,
    D_IN_REG_1__SCAN_IN;
  output Y, D_OUT_REG_7__SCAN_OUT, D_OUT_REG_6__SCAN_OUT,
    D_OUT_REG_5__SCAN_OUT, D_OUT_REG_4__SCAN_OUT, D_OUT_REG_3__SCAN_OUT,
    D_OUT_REG_2__SCAN_OUT, D_OUT_REG_1__SCAN_OUT, D_OUT_REG_0__SCAN_OUT,
    OLD_REG_7__SCAN_OUT, OLD_REG_6__SCAN_OUT, OLD_REG_5__SCAN_OUT,
    OLD_REG_4__SCAN_OUT, OLD_REG_3__SCAN_OUT, OLD_REG_2__SCAN_OUT,
    OLD_REG_1__SCAN_OUT, OLD_REG_0__SCAN_OUT, Y_REG_SCAN_OUT,
    STATO_REG_1__SCAN_OUT, STATO_REG_0__SCAN_OUT, D_IN_REG_8__SCAN_OUT,
    D_IN_REG_7__SCAN_OUT, D_IN_REG_6__SCAN_OUT, D_IN_REG_5__SCAN_OUT,
    D_IN_REG_4__SCAN_OUT, D_IN_REG_3__SCAN_OUT, D_IN_REG_2__SCAN_OUT,
    D_IN_REG_1__SCAN_OUT, D_IN_REG_0__SCAN_OUT;
  wire new_n59_, new_n60_, new_n61_, new_n63_, new_n64_, new_n65_, new_n67_,
    new_n69_, new_n71_, new_n73_, new_n75_, new_n77_, new_n86_, new_n87_,
    new_n100_;
  AND2X1   g00(.A(STATO_REG_0__SCAN_IN), .B(D_OUT_REG_7__SCAN_IN), .Y(D_OUT_REG_7__SCAN_OUT));
  INVX1    g01(.A(D_OUT_REG_6__SCAN_IN), .Y(new_n59_));
  INVX1    g02(.A(STATO_REG_0__SCAN_IN), .Y(new_n60_));
  NAND3X1  g03(.A(new_n60_), .B(STATO_REG_1__SCAN_IN), .C(D_OUT_REG_7__SCAN_IN), .Y(new_n61_));
  OAI21X1  g04(.A0(new_n60_), .A1(new_n59_), .B0(new_n61_), .Y(D_OUT_REG_6__SCAN_OUT));
  INVX1    g05(.A(D_OUT_REG_5__SCAN_IN), .Y(new_n63_));
  INVX1    g06(.A(STATO_REG_1__SCAN_IN), .Y(new_n64_));
  OR2X1    g07(.A(STATO_REG_0__SCAN_IN), .B(new_n64_), .Y(new_n65_));
  OAI22X1  g08(.A0(new_n65_), .A1(new_n59_), .B0(new_n60_), .B1(new_n63_), .Y(D_OUT_REG_5__SCAN_OUT));
  INVX1    g09(.A(D_OUT_REG_4__SCAN_IN), .Y(new_n67_));
  OAI22X1  g10(.A0(new_n65_), .A1(new_n63_), .B0(new_n60_), .B1(new_n67_), .Y(D_OUT_REG_4__SCAN_OUT));
  INVX1    g11(.A(D_OUT_REG_3__SCAN_IN), .Y(new_n69_));
  OAI22X1  g12(.A0(new_n65_), .A1(new_n67_), .B0(new_n60_), .B1(new_n69_), .Y(D_OUT_REG_3__SCAN_OUT));
  INVX1    g13(.A(D_OUT_REG_2__SCAN_IN), .Y(new_n71_));
  OAI22X1  g14(.A0(new_n65_), .A1(new_n69_), .B0(new_n60_), .B1(new_n71_), .Y(D_OUT_REG_2__SCAN_OUT));
  INVX1    g15(.A(D_OUT_REG_1__SCAN_IN), .Y(new_n73_));
  OAI22X1  g16(.A0(new_n65_), .A1(new_n71_), .B0(new_n60_), .B1(new_n73_), .Y(D_OUT_REG_1__SCAN_OUT));
  NAND2X1  g17(.A(STATO_REG_0__SCAN_IN), .B(D_OUT_REG_0__SCAN_IN), .Y(new_n75_));
  OAI21X1  g18(.A0(new_n65_), .A1(new_n73_), .B0(new_n75_), .Y(D_OUT_REG_0__SCAN_OUT));
  OR2X1    g19(.A(STATO_REG_0__SCAN_IN), .B(STATO_REG_1__SCAN_IN), .Y(new_n77_));
  AND2X1   g20(.A(new_n77_), .B(OLD_REG_7__SCAN_IN), .Y(OLD_REG_7__SCAN_OUT));
  AND2X1   g21(.A(new_n77_), .B(OLD_REG_6__SCAN_IN), .Y(OLD_REG_6__SCAN_OUT));
  AND2X1   g22(.A(new_n77_), .B(OLD_REG_5__SCAN_IN), .Y(OLD_REG_5__SCAN_OUT));
  AND2X1   g23(.A(new_n77_), .B(OLD_REG_4__SCAN_IN), .Y(OLD_REG_4__SCAN_OUT));
  AND2X1   g24(.A(new_n77_), .B(OLD_REG_3__SCAN_IN), .Y(OLD_REG_3__SCAN_OUT));
  AND2X1   g25(.A(new_n77_), .B(OLD_REG_2__SCAN_IN), .Y(OLD_REG_2__SCAN_OUT));
  AND2X1   g26(.A(new_n77_), .B(OLD_REG_1__SCAN_IN), .Y(OLD_REG_1__SCAN_OUT));
  AND2X1   g27(.A(new_n77_), .B(OLD_REG_0__SCAN_IN), .Y(OLD_REG_0__SCAN_OUT));
  NAND3X1  g28(.A(new_n60_), .B(STATO_REG_1__SCAN_IN), .C(D_OUT_REG_0__SCAN_IN), .Y(new_n86_));
  NAND3X1  g29(.A(STATO_REG_0__SCAN_IN), .B(new_n64_), .C(Y_REG_SCAN_IN), .Y(new_n87_));
  NAND2X1  g30(.A(new_n87_), .B(new_n86_), .Y(Y_REG_SCAN_OUT));
  OR2X1    g31(.A(STATO_REG_0__SCAN_IN), .B(new_n64_), .Y(STATO_REG_0__SCAN_OUT));
  OR2X1    g32(.A(STATO_REG_0__SCAN_IN), .B(STATO_REG_1__SCAN_IN), .Y(new_n100_));
  AND2X1   g33(.A(new_n100_), .B(X), .Y(D_IN_REG_8__SCAN_OUT));
  AND2X1   g34(.A(new_n100_), .B(D_IN_REG_8__SCAN_IN), .Y(D_IN_REG_7__SCAN_OUT));
  AND2X1   g35(.A(new_n100_), .B(D_IN_REG_7__SCAN_IN), .Y(D_IN_REG_6__SCAN_OUT));
  AND2X1   g36(.A(new_n100_), .B(D_IN_REG_6__SCAN_IN), .Y(D_IN_REG_5__SCAN_OUT));
  AND2X1   g37(.A(new_n100_), .B(D_IN_REG_5__SCAN_IN), .Y(D_IN_REG_4__SCAN_OUT));
  AND2X1   g38(.A(new_n100_), .B(D_IN_REG_4__SCAN_IN), .Y(D_IN_REG_3__SCAN_OUT));
  AND2X1   g39(.A(new_n100_), .B(D_IN_REG_3__SCAN_IN), .Y(D_IN_REG_2__SCAN_OUT));
  AND2X1   g40(.A(new_n100_), .B(D_IN_REG_2__SCAN_IN), .Y(D_IN_REG_1__SCAN_OUT));
  AND2X1   g41(.A(new_n100_), .B(D_IN_REG_1__SCAN_IN), .Y(D_IN_REG_0__SCAN_OUT));
  BUFX1    g42(.A(Y_REG_SCAN_IN), .Y(Y));
  BUFX1    g43(.A(STATO_REG_1__SCAN_IN), .Y(STATO_REG_1__SCAN_OUT));
endmodule


